apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-admin-operator-certificate
spec:
  secretName: "{{ .Release.Name }}-{{ .Values.adminOperator.secretName }}"
  commonName: "admin_operator"
  subject:
    countries:
      - US
  duration: {{ .Values.adminOperator.duration }}
  issuerRef:
    name: {{ .Release.Name }}-certifier-issuer
  keystores:
    pkcs12:
      create: true
      passwordSecretRef:
        key: password
        name: {{ .Release.Name }}-admin-operator-pkcs12-password
