apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-certifier-certificate
spec:
  secretName: "{{ .Release.Name }}-{{ .Values.certifier.secretName }}"
  commonName: "certifier.{{ .Values.dnsDomain }}"
  subject:
    countries:
      - US
  duration: {{ .Values.certifier.duration }}
  issuerRef:
    name: {{ .Release.Name }}-selfsigned-issuer
  isCA: true
