apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-controller-certificate
spec:
  secretName: "{{ .Release.Name }}-controller-tls"
  commonName: "*.{{ .Values.dnsDomain }}"
  subject:
    countries:
      - US
  duration: 87600h
  issuerRef:
    name: {{ .Release.Name }}-root-issuer
  dnsNames:
  - "*.{{ .Values.dnsDomain }}"
  - "*.nms.{{ .Values.dnsDomain }}"
