apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Release.Name }}-root-certificate
spec:
  secretName: "{{ .Release.Name }}-{{ .Values.root.secretName }}"
  commonName: "rootca.{{ .Values.dnsDomain }}"
  subject:
    countries:
      - US
  duration: {{ .Values.root.duration }}
  issuerRef:
    name: {{ .Release.Name }}-selfsigned-issuer
  isCA: true
